### ISSUE TITLE
 PROMISE_BUY_ITEM The sku was not found. Please fetch products first by calling getItems

### ISSUE THREAD

**Issue by ozcankrks** [dooboolab-community/react-native-iap#1220]
### Version of react-native-iap
^5.2.0
### Version of react-native
0.63.4
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
purchase test
### Actual behavior
purchaseErrorListener {"code": "PROMISE_BUY_ITEM", "debugMessage": "The sku was not found. Please fetch products first by calling getItems", "message": "The sku was not found. Please fetch products first by calling getItems", "productId": "android.test.purchased"}
PROMISE_BUY_ITEM The sku was not found. Please fetch products first by calling getItems
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
I am getting this error despite fulfilling all requests. 
The app has been added to Google play and the problem persists
Subscription and In-app purchase created on Google Play
Src Code : [https://notes.io/NrsC](https://notes.io/NrsC)

**Comment by ozcankrks** [comment]
problem solved. Detailed explanation of the solution on my blog https://ozcankrks.com/icerik.php?icerikid=58

**Comment by ozcankrks** [comment]
problem solved. Detailed explanation of the solution on my blog https://ozcankrks.com/icerik.php?icerikid=58

**Comment by PavanTank4631** [comment]
@ozcankrks what was the issue, your blog link is not working.

**Comment by ozcankrks** [comment]
> @ozcankrks what was the issue, your blog link is not working.

sorry. the blog is out of time. If you could not solve the problem, I would like to help if you send me your mail.

**Comment by Ilario17** [comment]
@ozcankrks how did you solve the problem?

**Comment by ozcankrks** [comment]
@Ilario17 The following code example works in my project. If you add it to your own project, it will work for you too.


`import * as RNIap from 'react-native-iap';`

```
state= {
        products:[],
        getsub:[],
        count:0,
        listprice:0,
        selectedItem:'none'
    }
```

```
async componentDidMount() {
     try {
          const products: Product[] = await RNIap.getProducts(itemSkus);
          const getsub: Subscription[] = await RNIap.getSubscriptions(itemSkus);
          this.setState({ getsub });
      } catch(err) {
          console.warn(err); // standardized err.code and err.message available
      }
      
  }
```

```
 requestPurchase = async (sku: string) => {
      try {
          await RNIap.requestPurchase(sku, false)
          .then((purchase)=>{
            console.log(purchase.purchaseToken)
            RNIap.finishTransaction(purchase, true);
            this.setState({ count:this.state.count+1 });
    
          })
          
          });
      } catch (err) {
          console.warn(err.code, err.message);
      }
  }

```
**example usage**
`this.requestPurchase("android.test.purchased")`

**tag me if you need more help**
**good luck**

**Comment by Ilario17** [comment]
My code works but every now and then some users get this error:

https://github.com/dooboolab/react-native-iap/issues/1051

**Comment by yasinugrl** [comment]
so to get the subscription/products you must have to release your app on Open Testing / Closed Testing / Internal Testing. once you are able to see your app on the play store as a beta available for testing then you are able to get the subscription or products in the array. Hope this will be helpful for anyone who faces this issue afterwards Cheers!

**Comment by aleksandarbos** [comment]
> so to get the subscription/products you must have to release your app on Open Testing / Closed Testing / Internal Testing. once you are able to see your app on the play store as a beta available for testing then you are able to get the subscription or products in the array. Hope this will be helpful for anyone who faces this issue afterwards Cheers!

to be ultra-precise according to https://www.iaphub.com/docs/set-up-android/configure-sandbox-testing/, only `Open` and `Closed` testing, **not** `Internal` , **it requires review by their side** before being able to do anything (internal doesn't require review). it's such a big hassle... 

thanks to authors for https://react-native-iap.dooboolab.com/docs/guides/troubleshooting/ 🥇

**Comment by kinloveko** [comment]
I solved this by wrapping up my object array into an object for example

```
string product = "com.example.app";
const arr =  [product];     // ["com.example.app"]
const skus = {arr};   // {["com.example.app"]}

await RNIap.requestPurchase({skus}, false);
```

I don't know why it should be named skus before putting it in the parameter.

**Comment by ozcankrks** [comment]
As I mentioned in 2021, it was crucial to be in test mode on Google Play to fetch products correctly. However, in the past few years, the usage of the package has changed. Now, both getProducts and getSubscriptions functions are used for iOS and Android. The purchasing process may vary depending on the platform, so make sure to handle them accordingly. For more details, you can check the updated documentation.

**Comment by ozcankrks** [comment]
> problem solved. Detailed explanation of the solution on my blog https://ozcankrks.herokuapp.com/makale/react-native-google-play-uygulama-ici-satin-alma-32

As I mentioned in 2021, it was crucial to be in test mode on Google Play to fetch products correctly. However, in the past few years, the usage of the package has changed. Now, both getProducts and getSubscriptions functions are used for iOS and Android. The purchasing process may vary depending on the platform, so make sure to handle them accordingly. For more details, you can check the updated documentation.

**Comment by ozcankrks** [comment]
> problem solved. Detailed explanation of the solution on my blog https://ozcankrks.herokuapp.com/makale/react-native-google-play-uygulama-ici-satin-alma-32

As I mentioned in 2021, it was crucial to be in test mode on Google Play to fetch products correctly. However, in the past few years, the usage of the package has changed. Now, both getProducts and getSubscriptions functions are used for iOS and Android. The purchasing process may vary depending on the platform, so make sure to handle them accordingly. For more details, you can check the updated documentation.

**Comment by ilirhushi** [comment]
make sure you are passing the `subscription.productId` on Android here and not `basePlanId` or anything else:

```
const productId = subscription.productId;

await requestSubscription({
        sku: productId,
        ...(offerToken && {
          subscriptionOffers: [{sku: productId, offerToken}],
        }),
      });
```
