### ISSUE TITLE
[TVOS] First time it prompts for login, second time it works

### ISSUE THREAD

**Issue by nriccar** [dooboolab-community/react-native-iap#2278]
**Description**
The first time I request a subscription, it prompts the Apple ID native login, and it fails with this error:
```
 ERROR  purchaseErrorListener error {"code": "E_UNKNOWN", "debugMessage": "An unknown error occurred", "message": "An unknown error occurred", "productId": "366804", "responseCode": "0"}
 ERROR  handleSubscribe error [Error: An unknown error occurred]
```

If I request the subscription again, it works. 
Any ideas?

Thanks!

**Comment by andresesfm** [comment]
Are you calling `getReceiptIOS()`?

**Comment by nriccar** [comment]
Isn’t that for the success listener after the payment went ok? This error is before that, right after entering password from apple id

**Comment by andresesfm** [comment]
Try the latest: https://github.com/dooboolab/react-native-iap/releases/tag/12.8.4 . I fixed an issue with the way we were getting the receipt that might have an impact on this issue

**Comment by nriccar** [comment]
Solved! Thanks!

**Comment by vishalhyperspace** [comment]
Hello 
I am facing same issue. my react-native-iap version is:  12.10.5

**Comment by andresesfm** [comment]
Same error?

**Comment by nriccar** [comment]
@vishalhyperspace can you try with 11.0.7?
```
"react-native-iap": "11.0.7"
```

Checked and my code is working with that version

**Comment by vishalhyperspace** [comment]
Solved. Work fine with 12.5.1

**Comment by vishalhyperspace** [comment]
@nriccar @andresesfm 
https://github.com/dooboolab-community/react-native-iap/issues/2473

Now I am getting this error. I am testing in sendbox.
