### ISSUE TITLE
[TVOS] Apple rejects the submitted archive 

### ISSUE THREAD

**Issue by nriccar** [dooboolab-community/react-native-iap#2385]
Hello, 

After implementing react-native-iap for a TVOS proejct, I get the following message. I submitted several apps with react-native-iap SDK without any problems, this is the first time I'm getting reject. Any ideas?

Apple reviewing team:
"After further reviewing your app, we have found that your app is currently out of compliance with the following guideline:
Guideline 2.1 - Performance - App Completeness
We found that your in-app purchase products exhibited one or more bugs which create a poor user experience. Specifically, your app doesn't show any in-app purchase item during the review. Please review the details and resources below and complete the next steps.
Review device details:
- Device type: AppleTV
- OS version: tvOS 16.3.2
Next Steps
When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment. The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code "Sandbox receipt used in production," you should validate against the test environment instead.
Resources
- Learn how to [set up](https://help.apple.com/app-store-connect/#/dev7e89e149d) and [test](https://developer.apple.com/documentation/storekit/in-app_purchase/testing_in-app_purchases_with_sandbox) in-app purchase products in the sandbox environment.
- For more information on receipt validation, see the [In-App Purchase FAQ](https://developer.apple.com/library/archive/technotes/tn2413/_index.html#//apple_ref/doc/uid/DTS40016228-CH1-RECEIPTURL).
- If your app makes a [SKReceiptRefreshRequest](https://developer.apple.com/documentation/storekit/skreceiptrefreshrequest) call and fails, do not retry the call. Assume the user does not have access. Continue by making the [addPayment](https://developer.apple.com/documentation/storekit/skpaymentqueue/1506036-addpayment) call.
- If your app makes a [SKReceiptRefreshRequest](https://developer.apple.com/documentation/storekit/skreceiptrefreshrequest) call to restore previously purchased in-app purchases, make sure the app calls [restoreCompletedTransactions](https://developer.apple.com/documentation/storekit/skpaymentqueue/1506123-restorecompletedtransactions) when the user selects the "Restore" button.
Best regards,
App Store Review"

I double checked that I can see subscribe button and its working from my Testflight environment

**Comment by andresesfm** [comment]
Have you tested in TestFlight?

**Comment by nriccar** [comment]
Yes I did and its working
