### ISSUE TITLE
requestPurchase TS definitions do not declare possible array return value

### ISSUE THREAD

**Issue by ulexxander** [dooboolab-community/react-native-iap#2426]
**Description**

Declaration of `requestPurchase` is as follows, it returns single `ProductPurchase` object.

```ts
const requestPurchase: (request: IAP.RequestPurchase) => Promise<void | IAP.ProductPurchase>
```

But on Android I actually got back array of products with single item.
Which makes sense, because on Android we can to pass multiple `skus` in parameters.

**Expected Behavior**

Typescript type definitions match runtime data.

**Environment:**

- react-native-iap: 12.10.5
- react-native: 0.71.6
- Platforms (iOS, Android, emulator, simulator, device): Android emulator (Pixel 4 API 30)

**To Reproduce**

1. Start flow: call `requestPurchase` for consumable product.
2. Log the return value of `requestPurchase` and complete the flow.

---

**Additional Context**

How I solved it in my code.

P.S. I know I should use listeners instead, currently I am only prototyping.

```ts
// useMutation
// requestPurchase({ skus: [mySku] });
onSuccess: (data) => {
  // NOTE: there seems to be bug in library typings.
  // which declare that requestPurchase function returns single ProductPurchase.
  // At least on Android it is not the case,
  // because actually array is returned (which makes sense, we are passing multiple skus in).
  const oneOrMorePurchases = data as
    | void
    | IAP.ProductPurchase
    | IAP.ProductPurchase[];

  const purchase = !oneOrMorePurchases
    ? null
    : Array.isArray(data)
    ? (data[0] as IAP.ProductPurchase)
    : data;
```

**Comment by coofzilla** [comment]
I have the same issue with this for `requestSubscription` the response is in an array for `android`
