### ISSUE TITLE
Error: You need wrap your app with withIAPContext HOC

### ISSUE THREAD

**Issue by musawarbilal786** [dooboolab-community/react-native-iap#2440]
> Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Environment:**

- react-native-iap
- react-native
- Platforms (Android)

**Comment by federaljules** [comment]
Did you wrap your app with the HOC?

https://react-native-iap.dooboolab.com/docs/api-reference/hooks

**Comment by musawarbilal786** [comment]
> Did you wrap your app with the HOC?
> 
> https://react-native-iap.dooboolab.com/docs/api-reference/hooks



> Did you wrap your app with the HOC?
> 
> https://react-native-iap.dooboolab.com/docs/api-reference/hooks

Have you worked on react native in app purchase ?? i am facing some issues, i want to discuss

**Comment by Hey-Feres** [comment]
Facing this same issue currently, any solution or idea?

Wrapping the App with HOC didn't solved it.

My code contain:
import {
  requestSubscription,
  SubscriptionPurchase,
  useIAP,
} from "react-native-iap";
```jsx

  const {
    connected,
    currentPurchase,
    currentPurchaseError,
    finishTransaction,
    getSubscriptions,
    subscriptions,
  } = useIAP();
```

**Comment by alordiel** [comment]
I've got the same error and while following the official repo example I found i missed [this](https://github.com/dooboolab-community/react-native-iap/blob/ef2a4a92de3525df4022e4739c0432236e21863b/IapExample/src/navigators/StackNavigator.tsx).
