### ISSUE TITLE
  IAP req ERROR %%% undefined right operand of 'in' is not an object

### ISSUE THREAD

**Issue by Prathameshlabde** [dooboolab-community/react-native-iap#2455]
Hello 

I have implemented react-native-iap (version:12.10.5) , react-native(version : 0.71.7)
I am trying to implement subscription by using requestSubscription() method, However I am getting below error     
IAP req ERROR %%% undefined right operand of 'in' is not an object
Below is my  block of code 
```
 requestSubscriptionFM = async (sku) => {
        await NetInfo.fetch().then(async (state) => {
            if (state.isConnected) {
                this.startLoader();
                // setBuyIsLoading(true);
                try {
                    console.log("subscription function123", sku);
                    await requestSubscription(sku)
                        .then(async (result) => {
                            console.log('IAP req sub', result);
                            if (platform === 'android') {
                                console.log("android sbscription");
                                this.setState({
                                    iapPurchaseToken: result.purchaseToken,
                                    iapPackageName: result.packageNameAndroid,
                                    iapProductId: result.productId,
                                });
                                // can do your API call here to save the purchase details of particular user
                            } else if (platform === 'ios') {
                                console.log("ios subscription", result.transactionReceipt);

                                this.setState({
                                    iapProductId: result.productId,
                                    iapReceipt: result.transactionReceipt,
                                });

                                // can do your API call here to save the purchase details of particular user
                            }
                            this.stopLoader();
                        })
                        .catch((err) => {
                            this.stopLoader();
                            console.warn(
                                `IAP req ERROR %%%%% ${err.code}`,
                                err.message,
                                // isModalVisible,
                            );
                            this.setState({ iapError: err.message });
                            // setError(err.message);
                        });
                } catch (err) {
                    // setBuyIsLoading(false);
                    this.stopLoader();

                    console.warn(`err ${err.code}`, err.message);
                    this.setState({ iapError: err.message });
                    // setError(err.message);
                }
            }
        });
    };
```

Please suggest to fix this issue

**Comment by mansimakwana25** [comment]
Use requestSubscription method like below

await requestSubscription({sku}).then(async (result) => { 
//your code 
})

**Comment by Prathameshlabde** [comment]
hello @mansimakwana25  as per your solution i had done the changes but now i am facing another issue 
error : - IAP req ERROR %%% undefined subscriptionOffers are required for Google Play subscriptions

    requestSubscriptionFM = async (sku) => {
        await NetInfo.fetch().then(async (state) => {
            if (state.isConnected) {
                this.startLoader();
                try {
                    RNIap.getProducts(sku);
                    await RNIap.requestSubscription({ sku })
                        .then(async (result) => {
                            console.log('IAP req sub', result);
                            if (Platform.OS === 'android') {
                                console.log("android sbscription");
                                this.setState({
                                    iapPurchaseToken: result.purchaseToken,
                                    iapPackageName: result.packageNameAndroid,
                                    iapProductId: result.productId,
                                });
                                // can do your API call here to save the purchase details of particular user
                            } else if (Platform.OS === 'ios') {
                                console.log("ios subscription", result.transactionReceipt);

                                this.setState({
                                    iapProductId: result.productId,
                                    iapReceipt: result.transactionReceipt,
                                });

                                // can do your API call here to save the purchase details of particular user
                            }
                            this.stopLoader();
                        })
                        .catch((err) => {
                            this.stopLoader();
                            console.warn(
                                `IAP req ERROR %%%%% ${err.code}`,
                                err.message,
                                // isModalVisible,
                            );
                            this.setState({ iapError: err.message });
                            // setError(err.message);
                        });
                } catch (err) {
                    // setBuyIsLoading(false);
                    this.stopLoader();

                    console.warn(`err ${err.code}`, err.message);
                    this.setState({ iapError: err.message });
                    // setError(err.message);
                }
            }
        });
    };

**Comment by mansimakwana25** [comment]
Hi @Prathameshlabde, yes for android you have to pass subscriptionOffers key in requestSubscription function, here is the sample code hope it will help

```
const offerToken = subscriptions[0].subscriptionOfferDetails[0].offerToken;
await requestSubscription({
    sku,
    subscriptionOffers: [{ sku, offerToken }],
})
```
					
subscriptions are the product array that you will find from getSubscriptions method

**Comment by sajorahasan** [comment]
Hi @mansimakwana25 can you please let me know how to pass obfuscatedProfileIdAndroid into the requestSubscription function.
I tried as below but then I got this error "Obfuscated profile id cannot be set without obfuscated account id."
`requestSubscription({
      obfuscatedProfileIdAndroid: user?.id?.toString(),
      sku,
      subscriptionOffers: [{sku, offerToken}],
    })`
