### ISSUE TITLE
The certificate for this server is invalid. You might be connecting to a server that is pretending to be “mzstorekit-sb.itunes.apple.com” which could put your confidential information at risk

### ISSUE THREAD

**Issue by Chandrakala-B** [dooboolab-community/react-native-iap#2537]
**Description**
getAvailablePurchases().catch(err => {
            console.log("getAvailablePurchases err:: ", err);
 });
When we hit above method we are getting this error - The certificate for this server is invalid. You might be connecting to a server that is pretending to be “mzstorekit-sb.itunes.apple.com” which could put your confidential information at risk.

Can anyone help me on this.

**Expected Behavior**

**Screenshots**

**Environment:**

- react-native-iap: 12.10.7
- react-native: 0.68.2
- Platforms (iOS, Android, emulator, simulator, device): iPhone 11

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by udkumar** [comment]
I am getting the same issue:

Environment:

react-native-iap: 12.10.7
react-native: 0.70.6
Platforms (iOS, Android, emulator, simulator, device): iPhone 13

IAP is working in a debug build but after uploading to testFlight it is showing the same error.

**Comment by arshadrGit** [comment]
We were also facing this issue since yesterday. But today it got fixed automatically. it could be apple backend issue.

**Comment by Chandrakala-B** [comment]
Yes its working.
