### ISSUE TITLE
getProducts always empty on android

### ISSUE THREAD

**Issue by kriptonhaz** [dooboolab-community/react-native-iap#2545]
I tried to getProducts in android always returns empty array while on ios is already working, already read the troubleshooting page and followed all of the GitHub comments but there's no change.

here is the gist of the code
```
try {
      const response = await IAP.getProducts({skus: productId});
      console.log(response);
} catch (err) {
      console.log(err);
}
```

what I do so far

- [x] upload the signed apk to activate the in-app product
- [x] add billing permission on android manifest
- [x] add product in the in-app product, after set the product id and price then I already activate it
- [x] already added the license tester on the play console
- [x] already use a real device for testing, either debug or release mode

my environtment

```
react-native 0.70.6
react-native-iap 12.10.5
android version 12
```

thanks for the help

**Comment by ddambrosi90** [comment]
I’m having the same problem, have you found a solution? @kriptonhaz

**Comment by c100k** [comment]
Is `productId` an array ? Otherwise, maybe try with `await IAP.getProducts({skus: [productId]})`

**Comment by kriptonhaz** [comment]
> Is `productId` an array ? Otherwise, maybe try with `await IAP.getProducts({skus: [productId]})`

productId is already an array of strings, and still got an error, and using those gist of code is showing an error from typescript

> I’m having the same problem, have you found a solution? @kriptonhaz

still blank, I tried to add another product and still not receive any result

**Comment by JignashaJoshi** [comment]
Facing the same problem in Android only. Did anyone find solution?

**Comment by indranildas19** [comment]
Having the same issue.

**Comment by kriptonhaz** [comment]
after I tried to submit it to the internal test track saw some kind of error stating something like "You need to fill in the physical address for selling in-app product" After I filled it in, waited for a while, and tested it again, the product now is appearing. hopefully, it will help the other to resolve the same issue as mine. thanks
