### ISSUE TITLE
PBL 6 support

### ISSUE THREAD

**Issue by noway** [dooboolab-community/react-native-iap#2557]
**Description**

PBL 6 has been released in May and Google has 2 year update support window for every version. `react-native-iap` will eventually need to upgrade to PBL 6, the sooner the better.

**Expected Behavior**

Have `RNIap_playBillingSdkVersion` to be more than or equal 6 in here: https://github.com/dooboolab-community/react-native-iap/blob/245d64e9454e8815a15b1412e379d7fe22dcba3c/android/gradle.properties#L9 

**Screenshots**

N/A

**Environment:**

- react-native-iap: 12.10.8
- react-native: 0.68.2
- Platforms (iOS, Android, emulator, simulator, device): Android

**To Reproduce**

N/A

---

**Additional Context**

Upgrade guide here: https://developer.android.com/google/play/billing/migrate-gpblv6#update-google

**Comment by scuti-dai** [comment]
+1

**Comment by lonasozo** [comment]
+1

**Comment by hyochan** [comment]
Closes #2598 

I've upgraded the billingClient and check that nothing breaks. However, we should implement new feature in new billingClient in the future.

Many thanks.
