### ISSUE TITLE
[iOS] How can I implement Apple Promotional Offers

### ISSUE THREAD

**Issue by rebeccahsu** [dooboolab-community/react-native-iap#2560]
**Description**

I want to implement iOS Promotional Offers with the library. I've set up the subscription items and I can get the discounts array from `getSubscriptions()`, but I don't know how to request subscription with the discount in RNIap.

If I do `requestPurchase({ sku, withOffer: { identifier: '...', keyIdentifier: '...', nonce: '...', signature: '...', timestamp: '...' } })`, the discount doesn't apply and the price remains the original one. I wonder what are the applicable/appropriate parameters for `requestPurchase()`.

**Expected Behavior**

Implementing iOS promotional offers

**Environment:**

- react-native-iap: 11.0.0
- react-native: 0.66.4
- Platforms (iOS, Android, emulator, simulator, device): iOS

**Additional Context**
[Official Doc of Apple Promotional Offers](https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/subscriptions_and_offers/implementing_promotional_offers_in_your_app)

**Comment by rebeccahsu** [comment]
Found it. should be:
```
RNIap.requestSubscription({
  sku: '...',
  appAccountToken: '...'
  withOffer: {
     identifier: '...',
     keyIdentifier: '...',
     nonce: '...',
     signature: '...',
     timestamp: '...'
  }
})
```

**Comment by suyogyadavindexnine** [comment]
@rebeccahsu Hey, I need some help here. Where can I get the keyIdentifier, nonce, signature and timestamp?

when I call `getSubscriptions ()` I get the discount object which looks like this - 

`
      {
        "localizedPrice": "$9.99",
        "type": "SUBSCRIPTION",
        "numberOfPeriods": "1",
        "price": "9.99",
        "paymentMode": "PAYUPFRONT",
        "subscriptionPeriod": "YEAR",
        "identifier": "firstYearOffer"
      }
  `
    
I am not able to understand the process of applying the offer for IOS. Can you please explain a bit?

Thanks in advance.

**Comment by rebeccahsu** [comment]
Hi @suyogyadavindexnine, for the "withOffer" object, you need to get the signature from your backend.

First generate the key in App Store Connect:
https://developer.apple.com/help/app-store-connect/configure-in-app-purchase-settings/generate-keys-for-in-app-purchase.
And then follow this tutorial on the server to get the data you need:
https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/subscriptions_and_offers/generating_a_promotional_offer_signature_on_the_server.

Hope this helps!

**Comment by caoyongfeng0214** [comment]
> Found it. should be:
> 
> ```
> RNIap.requestSubscription({
>   sku: '...',
>   appAccountToken: '...'
>   withOffer: {
>      identifier: '...',
>      keyIdentifier: '...',
>      nonce: '...',
>      signature: '...',
>      timestamp: '...'
>   }
> })
> ```

Always pop up `Unable to Purchase`. Seems to be a signature error caused by the `appAccountToken`.
@suyogyadavindexnine  Can you help me? https://github.com/dooboolab-community/react-native-iap/discussions/2629

**Comment by gkpo** [comment]
Hey all,
Trying to figure out how to subscribe a user to an offer (1 Month Free) given the user is already within a yearly subscription (which is auto renew).
Would the requestSubscription take that into account and only add the offer to the already running subscription ?
Thanks in advance

**Comment by Akifcan** [comment]
hi @rebeccahsu  do you now how can I  get the applicationUsername
I tried default value in here
https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/subscriptions_and_offers/generating_a_promotional_offer_signature_on_the_server
```
{
    "appBundleID": "",
    "productIdentifier": "",
    "offerId": "",
    "applicationUsername": "8E3DC5F16E13537ADB45FB0F980ACDB6B55839870DBCE7E346E1826F5B0296CA"
}
```

but I always get not eligible for offer error

**Comment by eedeebee** [comment]
I have a sub with a promotional offer defined in my StoreKit config file (sync'd from App Store).  When I look at the subscription from getSubscriptions() it's missing those details.  It this expected @rebeccahsu ?

**Comment by rebeccahsu** [comment]
Hi @caoyongfeng0214 @Akifcan
I take the user id in my app (nothing special, just a UUID) as the `applicationUsername` used to generate the `withOffer` item as well as the `appAccountToken` used in `RNIap.requestApplication`. Not sure if this info helps.

**Comment by rebeccahsu** [comment]
Hi @eedeebee 
I think the details should be included... >< Yet in my experience it needs some time to sync'd from App store, and the cache may influence the results too.
