### ISSUE TITLE
E_IAP_NOT_AVAILABLE

### ISSUE THREAD

**Issue by StanislavPavlov** [dooboolab-community/react-native-iap#2592]
**Description**

When using `withIAPContext` an error **E_IAP_NOT_AVAILABLE** occurs or when calling `initConnection` on iOS device 17. But it works in the xcode simulator.

**Screenshots**

![photo_2023-10-23_20-28-51](https://github.com/dooboolab-community/react-native-iap/assets/43149820/7a50f75f-b747-40da-9974-6393ca3907e7)

**Environment:**

- react-native-iap: **12.10.8**
- react-native: **0.70.5**
- Platforms (iOS, Android, emulator, simulator, device): **iOS 17 device**.

**Comment by lluisandreu** [comment]
@StanislavPavlov Why is this issue closed? I have now this issue on iOS 17 when using rniap 12

**Comment by lluisandreu** [comment]
@StanislavPavlov I discovered the issue, I had this function flushFailedPurchasesCachedAsPendingAndroid() called on an iOS device, I wrapped it in a Platform.Os conditional.
However, this functions should not throw a critial error like this.

**Comment by StanislavPavlov** [comment]
@lluisandreu In my case, the problem was in expo.  My mistake for not pointing that out here. Link to a solution to similar problems when running native libraries in eas: https://stackoverflow.com/a/73159706/570612.
this was suggested in the same problem, so it wasn't about the iOS version: https://github.com/dooboolab-community/react-native-iap/issues/2084#issuecomment-1304090763
