### ISSUE TITLE
Android Purchase Error: 'skus is required for Android purchase' Despite Provided skus Array

### ISSUE THREAD

**Issue by ian-hank** [dooboolab-community/react-native-iap#2600]
**Description**

When attempting to initiate a purchase on Android using the requestPurchase function from the react-native-iap package, the function throws an error stating that 'skus is required for Android purchase'. This occurs even when the skus property is present and contains a non-empty array. The issue persists even when hardcoding the skus array directly into the function call.

**Expected Behavior**

The expected behavior is for the requestPurchase function to accept the skus array and proceed with the purchase flow without throwing an error, as the necessary skus array is provided. iOS is able to proceed and continue with the purchase (indicating the headers are accurate for iOS). 

**Screenshots**
Screenshot shows all methods that I have tried (uncommented them all at once so it is easier to view in the screenshot). 
<img width="478" alt="image" src="https://github.com/dooboolab-community/react-native-iap/assets/57643516/f434c367-499a-41a0-babb-0aae50122ef7">

**Environment:**

- react-native-iap: 12.0.0 (have tried others, both up and down)
- react-native: 0.72.3
- Platforms: Android (emulator and real device tried, both with play store enabled)

**To Reproduce**

Set up a call to requestPurchase with a valid skus array on an Android platform.
Execute the purchase flow to initiate a purchase.
Observe the error 'skus is required for Android purchase' being thrown.
Here is the code snippet used to reproduce the error:

```
const handlePurchase = async () => {
  const params = {
    skus: ['product_id_hardcoded_for_testing'],
  };

  try {
    await requestPurchase(params);
  } catch (error) {
    console.log("Purchase Error:", error);
  }
};

handlePurchase();
```
---

**Additional Context**
The source code from react-native-iap for requestPurchase indicates I am failing in one of these two places, but I can not seem to figure out why or where. 
```if (isAmazon) {
          if (!('sku' in request)) {
            throw new Error('sku is required for Amazon purchase');
          }
          const {sku} = request;
          return RNIapAmazonModule.buyItemByType(sku);
        } else {
          if (!('skus' in request) || !request.skus.length) {
            throw new Error('skus is required for Android purchase');
          }
 ```

The issue was first noticed on 11/2/2023, and it has been consistently reproducible on our environment.
The problem occurs regardless of whether the skus parameter is hardcoded or dynamically set (whether through platform select, or a platform.OS ternary). 

The code works for iOS and purchases are able to go through using the platform select method. The source code shows that it is not even making it to the request which means that the **skus** is not valid in the request, or has a length of 0. I have tried all manners of passing it in, but to no avail.

**Comment by ram-vilash** [comment]
@hyochan Could you please look into this, getting the same issue for me as well.

**Comment by danleveille** [comment]
It looks like Android expects the property `skus` (an array of strings) rather than `sku` (a single string) like iOS does.

But the documenation and examples say to use `sku` regardless of platform?

I did this as a temporary workaround (it works) since I'm not sure what the intended fix for the parameter should be.
```js
      // sku = "mysku"
      if (Platform.OS === 'ios') {
          await requestPurchase({sku});
      } else if (Platform.OS === 'android') {
          await requestPurchase({ skus: [sku] });
      }
```

**Comment by ian-hank** [comment]
Yeah that's the patterns I have noticed too. Many of the examples including those directly below the method for usage in the package show that you only need to provide a sku and nowhere does it actually indicate (besides the source code and eventual error) that android is looking for a parameter `skus: string[]`.

I eventually figured this out through other opened issues previously for the package, but alas here I am with the issue still happening after trying every single seemingly possible combination of parameters. The error message itself should probably be provided better, as I see many posts regarding people getting tripped up by it (easy to find a resolution though with all the posts). 

In my testing the farthest I have gotten on android is actually using the iOS method of `sku: productID`. This allows the play store to actually popup and throw a new error that the product does not exist. I will show all of my methods and their results below quickly just for reference, maybe someone has experienced the same as me before and I wonder if it's something with our google play console setup. 

### **The result of a getProducts call** 
Indicating there is valid products and product ids to purchase coming down from our google play console...
<img width="553" alt="image" src="https://github.com/dooboolab-community/react-native-iap/assets/57643516/7d4eab7f-e887-4cfd-9ba9-f7f6ed0d605a">

**Test 1**
```
const params = Platform.select({
  ios: {
    sku: "test01",
    andDangerouslyFinishTransactionAutomaticallyIOS: false,
  },
  android: {
    skus: ["test01"],
  },
  default: {}
  })
  const purchaseResult = await requestPurchase(params)

"Error Caught: skus is required for android purchase"
```

**Test 2**
```
if (Platform.OS === 'ios') {
    await requestPurchase({"test01"});
} else if (Platform.OS === 'android') {
    await requestPurchase({ skus: ["test01"] });
}

"Error Caught: skus is required for android purchase"
```


**Test 3**
```
await requestPurchase({ skus: ["test01"] })

"Error Caught: skus is required for android purchase"
```

**Test 4**
```
await requestPurchase("test01")

"Error Caught: skus is required for android purchase"
```

**Test 5 (farthest i have gotten)**
```
await requestPurchase({ sku: "test01"})
Play Store Modal Appears with "The item you were attempting to purchase could not be found".
```

**Comment by ian-hank** [comment]
It seems that Android now accepts the same parameters as apple. This flow works to purchase on both iOS and Android. 

```
const handlePurchase = async (productId: string) => {
  const params = Platform.select({
    ios: {
      sku: productId,
      andDangerouslyFinishTransactionAutomaticallyIOS: false,
    },
    android: {
      sku: productId,
    },
    default: {}
  })
  await requestPurchase(params)
}
```

Previously, the error 'The item you were attempting to purchase could not be found' encountered during testing was linked to a distinct, documented issue. This occurred while using the Android emulator, where I was logged into the Play Store with the same developer account as registered in the Play Store Console. Although this email was part of the payment testers group, the issue persisted. However, when I switched to a secondary test account, the purchase process completed successfully.

**Comment by PouyaLitkouhi** [comment]
Hi, 
Still happening on 12.12.1
Same behavior, I had to use this workaround
```
const purchaseRequest = async sku => {
    if (isAndroid()) {
      await requestPurchase({ skus: [sku] });
    } else {
      await requestPurchase({ sku });
    }
  };
  ```

**Comment by OrestKlymko** [comment]
What is the solution?

**Comment by fexx** [comment]
I solved it this way.

react-native-iap: "^14.5.0"

```
requestPurchase({
    request: {
        android: {
        skus: [sku.id],
        },
    },
    type: 'subs',
});
```
