### ISSUE TITLE
getSubscriptions() return empty if debug without Storekit

### ISSUE THREAD

**Issue by hyu-uit** [dooboolab-community/react-native-iap#2617]
> Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
I implemented react-native-iap and config in Appstore Connect. I used Storekit to test it:
 1. I created a storekit file and sync with apple developer account
 2. My storekit can sync and get subscriptions I added in Appstore Connect
 3. I change scheme options with storekit configuration
 4. It works perfectly

Then I want to test with Sandbox account, so I edited scheme to none with storekit configuration. But when I debug on my phone, do not have any subscriptions fetched!

When set up in Appstore connect, I agreed with Terms but not add bank account. My question is: "Does missing adding bank account is the problem in my case?"

**Expected Behavior**
Can fetch subscriptions without storekit config.

**Screenshots**

**Environment:**
- react-native-iap:
- react-native:
- Platforms (iOS, Android, emulator, simulator, device): ios 15.5, real phone

Thank you so much

**Comment by hyu-uit** [comment]
EDIT: I solve it by adding bank account and taxs (status will change to active)!
Thanks

**Comment by cynde** [comment]
where do you add your bank account ? i cannot find it in appstoreconnect @hyu-uit
