### ISSUE TITLE
Is it free plugin?

### ISSUE THREAD

**Issue by developer1031** [dooboolab-community/react-native-iap#2639]
Hello.
I was using react-native-iaphub.
It is not free. My client angry about it.
Could you tell me it is free even deploy to Apple and Google Store?
Thanks.

**Comment by dmk3141618** [comment]
As far as I know, this is completely free.

**Comment by hyochan** [comment]
Hi there! Yes this is MIT License and free for all~
We recently removed `iaphub` from our documentation because of that reason and it haven't sponsored our project.
