### ISSUE TITLE
getSubscriptions returns localizedPrice containing "," instead of "." in prices

### ISSUE THREAD

**Issue by Garvnanwani** [dooboolab-community/react-native-iap#2646]
**Description**

"localizedPrice" key returned in subscription array contains "," instead of "." in prices of Brazil, Europe and monthly prices in US. So if the price in app store is R$ 149.90, localizedPrice returns R$ 149,90. 

However for Indian rupees and US yearly prices it returns the correct value i.e Rs 3,999 gets returned as Rs 3,999 but it treats "." in app store prices as ","

The price key in the subscription object is fine, it contains "149.9" but the localizedPrice is wrong, it returns "R$ 149,90"

**Expected Behavior**

localizedPrice should return the correct pricing as "," and "." in price makes a huge difference. They wont be charged 149,90 but they will see 149,90 in the app. And to show local price we have to use localizedPrice instead of price.

**Screenshots**
This the subscription object for yearly and monthly subscription with Brazil region. "R$ 149,90" should be "R$ 149.90" in localizedPrice.

![image](https://github.com/dooboolab-community/react-native-iap/assets/36405030/8b6eabf4-9bdd-48fe-87a6-c40b9ecf0d3a)

**Environment:**

- react-native-iap: 12.10.7
- react-native: 0.71.10
- Platforms (iOS, Android, emulator, simulator, device): iOS 17.2

**To Reproduce**

1. Use price with "." in app store like "149.90"
2. Call setSubscriptions()
3. Use Brazil region or sandbox user
4. Check the localizedPrice, it is coming "R$ 149,90" instead of "R$ 149.90"

---

[Optional] **Additional Context**

Is this the correct behavior or am I missing something? 
Can anyone please guide me

**Comment by DevYuns** [comment]
@Garvnanwani I have similar problem. Did you solve it?
