### ISSUE TITLE
[ios] purchaseUpdatedListener trigger is not called after confirming the purchase

### ISSUE THREAD

**Issue by Z-Hayk** [dooboolab-community/react-native-iap#2647]
**Description**

Each time after a purchase, the purchase confirmation window opens again.
purchaseUpdatedListener trigger is not called after confirming the purchase.

**Expected Behavior**

After confirmation of purchase should be called purchaseUpdatedListener trigger

**Screenshots**

https://streamable.com/72tvz6
And so on forever!

**Environment:**

```
    "react": "18.2.0",
    "react-native": "0.73.0",
    "react-native-iap": "12.12.1",
```
- react-native-iap:
- react-native:
- Platforms (iOS, simulator):

**To Reproduce**

Wrote everything according to the documentation:
https://react-native-iap.dooboolab.com/docs/guides/purchases

**Comment by SnowingFox** [comment]
how to solve it ？

**Comment by zachrussell12** [comment]
Also having this issue. Trying to find other fixes. Will report back if I find something that works.
