### ISSUE TITLE
Repeatedly prompted for the purchase in react-native-iap IOS. No callback on the listener

### ISSUE THREAD

**Issue by aabhiitatva** [dooboolab-community/react-native-iap#2654]
> Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
I am facing an issue while integrating react-native-iap on iOS. I am able to fetch the products I created on app store connect.
The purchase popup appears after clicking on the purchase button and entering my Apple credentials. However, after a successful payment, there is no callback on the listener. After that, I'm repeatedly prompted for the purchase, regardless of how many times I enter my password. And if I cancel the payment, I get a proper response on my currentPurchaseError state.

**Expected Behavior**
For purchase to complete (either fail or pass). And receive a callback from the listener. If not at least it should not prompt for payment again.

**Screenshots**

<img width="406" alt="1" src="https://github.com/dooboolab-community/react-native-iap/assets/154986245/ece314f1-628e-43cd-8928-a0b370857bdc">

<img width="399" alt="2" src="https://github.com/dooboolab-community/react-native-iap/assets/154986245/768a491e-e44a-453a-bfd6-912b3ed76c6b">

<img width="407" alt="3" src="https://github.com/dooboolab-community/react-native-iap/assets/154986245/fc367b05-1d2e-4cc1-9c11-abfbe089a8ae">

**Environment:**
- "react": "17.0.2"
- "react-native": "0.66.5"
- "react-native-iap": "^12.12.1"
- Platforms (iOS, simulator, device):

**To Reproduce**
Below is the code for my PurchaseScreenIOS screen

![4](https://github.com/dooboolab-community/react-native-iap/assets/154986245/d48da370-a4c5-4bf4-8ab0-f0d55d089b57)
![5](https://github.com/dooboolab-community/react-native-iap/assets/154986245/674d772b-ccdc-4c35-b0de-3e5e157dfc12)
![6](https://github.com/dooboolab-community/react-native-iap/assets/154986245/452a9791-db59-430a-b18a-cdb913797255)

I have selected for In-App Purchase in Xcode and created products on apple app store connect.

---

[Optional] **Additional Context**

**Comment by aabhiitatva** [comment]
Steps to resolve.
1) use a physical device for testing
2) requestPurchase({sku: id})
      .then(async data => {
        console.log("Purchase was completed");
      })
      .catch(err => {
        console.log("Purchase was not completed");
      });
 3) No need for listeners
 4) Use "react-native-iap": "^12.10.7"

**Comment by GaNiziolek** [comment]
Hello @aabhiitatva, I have the same issue here, but I don't have access to a physical device, only an emulator.

Do you know if this issue is strictly related to the emulator? I've followed the steps you describe to resolve but the problem persists.
