### ISSUE TITLE
getProducts returns undefined.

### ISSUE THREAD

**Issue by sleep9** [dooboolab-community/react-native-iap#2667]
> Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

getProducts returns undefined for consumables despite being setup.
I am expecting an array of consumables returned by getProducts.

**Screenshots**
App agreements have been completed. 
<img width="1336" alt="Screenshot 2024-01-04 at 16 08 45" src="https://github.com/dooboolab-community/react-native-iap/assets/60583270/0d6a7c21-27b2-4cca-aedc-de996e72b1f3">
Consumables and their namespaces are on appstoreconnect
<img width="1092" alt="Screenshot 2024-01-04 at 16 06 21" src="https://github.com/dooboolab-community/react-native-iap/assets/60583270/3ebdae90-46cc-4e45-a14e-473b13791c05">
Added .storekit file to build and synced with appstoreconnect
<img width="996" alt="Screenshot 2024-01-04 at 16 28 42" src="https://github.com/dooboolab-community/react-native-iap/assets/60583270/00afb832-4c49-434e-b628-e454ec1fca36">
Edited scheme to include .storekit file
<img width="932" alt="Screenshot 2024-01-05 at 09 31 47" src="https://github.com/dooboolab-community/react-native-iap/assets/60583270/35cd9b25-3dac-40cf-9b36-d6f55d7995bf">

And finally code...
`
const consumableSkus = 
  {skus:[
  'app.behest.iap.mistral.small.tokens.125k',
  'app.behest.iap.mistral.small.tokens.250k',
  'app.behest.iap.mistral.small.tokens.500k']};

let isConnected = false;
isConnected = await initConnection();
let res_products = await getProducts(consumableSkus);
console.log('res_products: ', res_products);
`
**Environment:**

- react-native-iap: ^12.12.1
- react-native:0.72.3
- Platforms (iOS, Android, emulator, simulator, device): iOS Device

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

The only thing I can think of that is problematic is that my bundle identifier is 
app.behest.behest-app and the prefix to my iap consumables are 
app.behest.iap.*
I cannot add hyphen to in app purchases so I cannot have the same prefix.

**Comment by sleep9** [comment]
I think I found the culprit but unsure how to proceed.
In app purchases is disabled (but selected) in my app bundle in the developer portal and Im not sure how to enable it.
<img width="555" alt="Screenshot 2024-01-05 at 14 58 25" src="https://github.com/dooboolab-community/react-native-iap/assets/60583270/c3dd4cf7-da6a-484a-8ffd-3c640dfcf68f">

**Comment by tandat1405** [comment]
hi @sleep9, try running the application on physical device, I just solve my same issue with it.

**Comment by jdbrinson** [comment]
Hello, @sleep9 I also had this issue. My problem was not realizing that there are two definitions for the `getProducts()` function: one directly imported from "react-native-iap" and the other from using the `useIAP()` hook. The former directly returns the products, the latter does not. 

```
//Option 1 
//returns products from the function call 
import {getProducts} from "react-native-iap"; 

function App() {
   skus = {skus: [...skus]};
   let returnedProducts = await getProducts(skus);
   console.log('products returned from function:", returnedProducts);
}
***********************************
//Option 2 
// does not return product from the function call
import {useIAP} from "react-native-iap";

function App() {

   skus = {skus: [...skus]};
   const {products, getProducts} = useIAP();

   getProducts()
   console.log('products variable updated by the hook:', products);
} 
```

Not sure which one you're using, but maybe try the other. Hope that helps!

**Comment by sleep9** [comment]
tyvm good sir! It worked. I doubt I would have ever found that.

**Comment by Tieu-Mai-Nhi** [comment]
@jdbrinson you're right, thanks
