### ISSUE TITLE
applicationUsername is not passed to iOS native method

### ISSUE THREAD

**Issue by hubertwang** [dooboolab-community/react-native-iap#2671]
> Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

We recently found that applicationUsername is missing from server to server notification from Apple.
After some investigation, we found that the interface for requestSubscription didn't pass applicationUsername to iOS native function.

javascript entry
https://github.com/dooboolab-community/react-native-iap/blob/7e7bac48745cf4ecb33eb5d1c45e7155406e5f5c/src/iap.ts#L761
It passed sku, andDangerouslyFinishTransactionAutomaticallyIOS, appAccountToken, quantity, offer.
``` javascript
          const purchase = transactionSk2ToPurchaseMap(
            await RNIapIosSk2.buyProduct(
              sku,
              andDangerouslyFinishTransactionAutomaticallyIOS,
              appAccountToken,
              quantity ?? -1,
              offer,
            ),
          );
```

iOS function buyProduct do have applicationUsername parameter.
https://github.com/dooboolab-community/react-native-iap/blob/7e7bac48745cf4ecb33eb5d1c45e7155406e5f5c/ios/RNIapIos.swift#L182

``` swift
    @objc public func buyProduct(
        _ sku: String,
        andDangerouslyFinishTransactionAutomatically: Bool,
        applicationUsername: String?,
        quantity: Int,
        withOffer discountOffer: [String: String]?,
        resolve: @escaping RCTPromiseResolveBlock = { _ in },
        reject: @escaping RCTPromiseRejectBlock = { _, _, _ in }
    )
```

**Expected Behavior**

Should pass applicationUsername to iOS bridge, and send to AppStore.

**Screenshots**

**Environment:**

- react-native-iap: 12.10.5
- react-native: 0.71.8
- Platforms (iOS, device):

**To Reproduce**

1. Call requestSubscription with {sku, applicationUsername}
2. Add break point in RNIapIos.swift L201, application should stop here.

---

[Optional] **Additional Context**

We may apply short-term solution, patch iap.ts locally, sending applicationUsername to iOS function first.
If no one fix this issue, I may create a pull request to fix issue when I have time.

**Comment by hubertwang** [comment]
Oh, I found that I made a mistake.
The key name to specify applicationUsername is appAccountToken.
I'll close this issue.

**Comment by itsaliraxa** [comment]
> Oh, I found that I made a mistake. The key name to specify applicationUsername is appAccountToken. I'll close this issue.

Which key you are talking about? It's a bit confusing.
