### ISSUE TITLE
[IOS] purchaseUpdatedListener callback not called when purchase success

### ISSUE THREAD

**Issue by SnowingFox** [dooboolab-community/react-native-iap#2679]
> Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
```ts
useEffect(() => {
    let purchaseUpdateSubscription: Nullable<EmitterSubscription>;
    initConnection()
      .then(async () => {
        console.log("success to connect app store");
        purchaseUpdateSubscription = purchaseUpdatedListener(
          async (purchase) => {
            const receipt = purchase.transactionReceipt;
            if (receipt) {
              try {
                await finishTransaction({ purchase, isConsumable: false });
              } catch (error) {
                console.error(
                  "An error occurred while completing transaction",
                  error,
                );
              }
            }
          },
        );
      })
      .catch((err) => {
        console.log("failed to connect app store", err);
      });

    const fetchProducts = async () => {
      await getProducts({
        skus: [...Coins],
      });
    };
    fetchProducts();

    return () => {
      purchaseUpdateSubscription?.remove?.();
      endConnection();
    };
  }, []);
```
purchaseUpdatedListener callback not called when purchase success

**Environment:**
  "react-native": "0.72.6",
    "react-native-iap": "^12.12.2",
- Platforms (iOS, Android, emulator, simulator, device):
IOS

**Comment by yedi97** [comment]
+1 the same issue

**Comment by Ajaykumar02** [comment]
> > Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.
> 
> **Description**
> 
> ```ts
> useEffect(() => {
>     let purchaseUpdateSubscription: Nullable<EmitterSubscription>;
>     initConnection()
>       .then(async () => {
>         console.log("success to connect app store");
>         purchaseUpdateSubscription = purchaseUpdatedListener(
>           async (purchase) => {
>             const receipt = purchase.transactionReceipt;
>             if (receipt) {
>               try {
>                 await finishTransaction({ purchase, isConsumable: false });
>               } catch (error) {
>                 console.error(
>                   "An error occurred while completing transaction",
>                   error,
>                 );
>               }
>             }
>           },
>         );
>       })
>       .catch((err) => {
>         console.log("failed to connect app store", err);
>       });
> 
>     const fetchProducts = async () => {
>       await getProducts({
>         skus: [...Coins],
>       });
>     };
>     fetchProducts();
> 
>     return () => {
>       purchaseUpdateSubscription?.remove?.();
>       endConnection();
>     };
>   }, []);
> ```
> 
> purchaseUpdatedListener callback not called when purchase success
> 
> **Environment:** "react-native": "0.72.6", "react-native-iap": "^12.12.2",
> 
> * Platforms (iOS, Android, emulator, simulator, device):
>   IOS

Can you please give more info on 
npm package version 
react native version 
mobile os version

**Comment by yedi97** [comment]
> > > Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.
> > 
> > 
> > **Description**
> > ```ts
> > useEffect(() => {
> >     let purchaseUpdateSubscription: Nullable<EmitterSubscription>;
> >     initConnection()
> >       .then(async () => {
> >         console.log("success to connect app store");
> >         purchaseUpdateSubscription = purchaseUpdatedListener(
> >           async (purchase) => {
> >             const receipt = purchase.transactionReceipt;
> >             if (receipt) {
> >               try {
> >                 await finishTransaction({ purchase, isConsumable: false });
> >               } catch (error) {
> >                 console.error(
> >                   "An error occurred while completing transaction",
> >                   error,
> >                 );
> >               }
> >             }
> >           },
> >         );
> >       })
> >       .catch((err) => {
> >         console.log("failed to connect app store", err);
> >       });
> > 
> >     const fetchProducts = async () => {
> >       await getProducts({
> >         skus: [...Coins],
> >       });
> >     };
> >     fetchProducts();
> > 
> >     return () => {
> >       purchaseUpdateSubscription?.remove?.();
> >       endConnection();
> >     };
> >   }, []);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > purchaseUpdatedListener callback not called when purchase success
> > **Environment:** "react-native": "0.72.6", "react-native-iap": "^12.12.2",
> > 
> > * Platforms (iOS, Android, emulator, simulator, device):
> >   IOS
> 
> Can you please give more info on npm package version react native version mobile os version

with me:
npm: 10.2.4
react-native: 0.73.3
mobile os: IOS 17

**Comment by EduardoBravoP** [comment]
Same here, but I could reproduce the purchase flow correctly on my physical device.
The emulator does not call the `purchaseUpdatedListener `

**Comment by SnowingFox** [comment]
I resolved it, because you should add goods in App Store App In Purchase page

**Comment by alexfoxy** [comment]
@SnowingFox what do you mean?

**Comment by aiwwz** [comment]
> I am having the exact same issue in sandbox environment and also testFlight. listener is called when testing with Xcode. Just wondering how production will work? Has anybody solved this for Sandbox/TestFlight to get listener to work?

Is the problem solved?
