### ISSUE TITLE
in expo getSubscriptions return an empty array

### ISSUE THREAD

**Issue by RickYangzz** [dooboolab-community/react-native-iap#2730]
<img width="1231" alt="image" src="https://github.com/dooboolab-community/react-native-iap/assets/38999212/56663130-a1fa-4b66-9a67-0ac3e1687cba">
I'd like to know if this internal status(not reviewed) is ok for me to test react-native-iap?

**Comment by RickYangzz** [comment]
Luckily, I have solved this problem finally.

**Comment by Jova266** [comment]
> Luckily, I have solved this problem finally.

Would you explain how?
