### ISSUE TITLE
Question Regarding Update to Google Play Billing Library Version 6

### ISSUE THREAD

**Issue by cddceo** [dooboolab-community/react-native-iap#2755]
I received a notification from Google stating that all new apps and updates to existing apps must use Google Play Billing Library version 6 or higher by August 31, 2024. They mentioned that from that date, any apps using versions lower than 6 will be blocked from publishing and updates.

Could you please let me know when React Native IAP will support Google Play Billing Library version 6? This update is crucial for us to continue publishing our app without interruptions.

**Comment by Marjoel** [comment]
Same here, waiting for updates to this post.

**Comment by MarkCSmith** [comment]
It looks like recent releases of react-native-iap already use version 6.x of the billing library.  See the definition of `RNIap_playBillingSdkVersion` here:
https://github.com/dooboolab-community/react-native-iap/blob/12.13.2/android/gradle.properties

Is there reason to believe otherwise?

**Comment by MarkCSmith** [comment]
@cddceo:  Interesting.  For what it is worth, I do not see a warning message in Google Play Console for my app.

**Comment by cddceo** [comment]
@MarkCSmith 
I got a hint from what you said.
I'll delete all node modules, update them again, and upload them back to the store.

**Comment by haresh4d** [comment]
I have updated my app and using the latest version of this library. Also uploaded the app but still the play console shows me the policy message.

**Comment by kauesedrez** [comment]
also here

**Comment by rnjsrnrdnjs** [comment]
Me too. Has anyone found a solution?

**Comment by LevisLuong** [comment]
I got same issue.

**Comment by hyochan** [comment]
Hello everyone,

Could anyone test the [12.14.1-rc.1](https://www.npmjs.com/package/react-native-iap/v/12.14.1-rc.1) release candidate and see if it works?

You can simply install the `next` version with the following command:

```bash
npm install react-native-iap@next
```

You can see the update in #2764

**Comment by hyochan** [comment]
If anyone has some time, could you please review #2764? Thank you!

**Comment by mayconline** [comment]
i believe that need change version at `android/app/build.gradle`



```
dependencies {
    def billingVersion = 7.0.0

    implementation "com.android.billingclient:billing:$billingVersion"
}
```

So I don't know if version 7 is supported yet

https://developer.android.com/google/play/billing/migrate-gpblv7?hl=pt-br

**Comment by hyochan** [comment]
> i believe that need change version at `android/app/build.gradle`
> 
> ```
> dependencies {
>     def billingVersion = 7.0.0
> 
>     implementation "com.android.billingclient:billing:$billingVersion"
> }
> ```
> 
> So I don't know if version 7 is supported yet
> 
> https://developer.android.com/google/play/billing/migrate-gpblv7?hl=pt-br

I think this is done here https://github.com/dooboolab-community/react-native-iap/pull/2764/files#r1640807011.
Am I missing something?

**Comment by endp01** [comment]
updating to 12.15.1 worked for me, just took google a few minutes to remove the warning message. make sure to update and roll out on all release tracks including internal testing.

**Comment by mayconline** [comment]
working for me too, but I needed to update react native to 0.74

**Comment by saumya66** [comment]
> working for me too, but I needed to update react native to 0.74

may i know what is your react native version and kotlinVersion ?

**Comment by mayconline** [comment]
> > working for me too, but I needed to update react native to 0.74
> 
> may i know what is your react native version and kotlinVersion ?

`    "react-native": "0.74.3",`
    
 ```
 'android/build.gradle'
 
 buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 24
        compileSdkVersion = 34
        targetSdkVersion = 34        
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.22"        
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin") 
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")       
    }
}
 
apply plugin: "com.facebook.react.rootproject"
```
    
```
`android/app/build.gradle
`

apply plugin: "org.jetbrains.kotlin.android"
```

**Comment by daybreaker** [comment]
If I'm stuck on RN 0.68.5 for the next few months, do I have any solutions?
