### ISSUE TITLE
 Fix iap promoted product from cold start

### ISSUE THREAD

**Issue by KP-MobileTechie** [dooboolab-community/react-native-iap#2786]
It's not working in the latest version when user come from the terminate state it's not working(listener not called).

**Comment by hyochan** [comment]
On which platform are you experiencing this issue, and what is the exact version of `react-native-iap` you are using? Providing more detailed information would be very helpful.

**Comment by KP-MobileTechie** [comment]
I am facing this issue in version 8.6.7 I am updating my library from 7.5.6 to 8.6.7 Because in previous version, I also facing this issue, so I try new reason which have better downloads, but still facing this issue

**Comment by KP-MobileTechie** [comment]
Library is working when APP is on background mode but if I killed APP and open via promotional link, then it’s not work

**Comment by KP-MobileTechie** [comment]
**### I called that function in componentDidMount** 

 ```
 async SubscriptionPromotion() {
    RNIap.initConnection().then((canMakePayments) => { console.log('Can make payments:', canMakePayments); }).catch((error) => { console.error('Error initializing connection:', error); });
    try {
      this.subscription = RNIapEmitter.addListener('iap-promoted-product', async () => {
  

        if (Message.STAGING) {
          this.props.navigation.navigate(Message.screen_sales_page);
          await RNIap.buyPromotedProductIOS(); 
        }
        const productId = await RNIap.getPromotedProductIOS();
        console.log("🚀 ~ RNIapEmitter.addListener ~ productId:", productId)

        if (productId !== null) {
          try {

            this.props.navigation.navigate(Message.screen_sales_page);
            await RNIap.buyPromotedProductIOS(); 
          } catch (error) {
            console.log("🚀 ~ RNIapEmitter.addListener ~ error:", error)
          }
        }
      });
    } catch (e) {
      console.log("🚀 ~ SubscriptionPromotion ~ error:", e)
    }
  }
```
  
  **### Remove the listener in componentWillUnmount** 
  
```
   componentWillUnmount() {
    this.subscription.remove()
  }
  
```

**React native version :- 0.63.4**
**React native IAP Version :-^7.0.3**

**- I am encountering an issue where the listener does not work when I terminate app and open by this link itms-services://?action=purchaseIntent&bundleId=com.example.app&productIdentifier=product_name.**

**Comment by KP-MobileTechie** [comment]
### Help me out for this issue because I have dependent your library
@ngocdaothanh @rikur @jgillick @neilco @0916dhkim @13arturbruno @AmauryLiet @breathingearth @chloe-codes1 @cometkim @cristoferfb @dipinarora9 @edTheGuy00 @emilioicai @fjcaetano @geoseong @ghsdh3409 @hankkuu @heyman333 @hyochan @jeebb @jeremybarbet @kwmt @lgraubner @LinusU @M46N3 @maxgmer @MehndirattaPiyush @mifi @mym0404 @pauluhn @pietro909 @RaeesBhatti @rinku-k @Rockvole @RZulfikri @sajithneyo @sayem314 @unolife @vshab @vuonghv @xPutnikx @yjb94 @yoali11 @Zamorite @ZeroCho @zxcpoiu

**Comment by sayem314** [comment]
Please stop spamming. You are annoying everyone with so much mentions. Creator already replied on your issue and give him time to help. No one gets paid for developing such free and open source modules.

**Comment by KP-MobileTechie** [comment]
Hi,

I sincerely apologize for my previous message; it was not my intention to spam. I have been working on this issue for many days, and my app relies heavily on this functionality. If possible, please help me out.

**Comment by ZeroCho** [comment]
@KP-MobileTechie I'm not related to this library. Why did you mention me? If you have problems that are very urgent, fix yourself if you are a programmer.
