### ISSUE TITLE
Android getSubscriptions and getProducts always return an empty array

### ISSUE THREAD

**Issue by leminhcse** [dooboolab-community/react-native-iap#2792]
> Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

Android getSubscriptions and getProducts always return an empty array on Android device

**Expected Behavior**

Expecting to get an array of getSubscriptions and getProducts

**Screenshots**
<img width="1324" alt="Screenshot 2024-07-01 at 15 52 58" src="https://github.com/dooboolab-community/react-native-iap/assets/45330126/f7aed2a6-f644-4798-b21d-50532d4904da">

**Environment:**

- react-native-iap: 12.15.0
- react-native: 0.72.7
- Platforms (iOS, Android, emulator, simulator, device): Android

```
    const fetchProducts = async (skus: string[]) => {
      try {
        const connection = await initConnection();
        if (connection) {
          const fetchedSubs = await getSubscriptions({skus});
          const fetchedBTO = await getProducts({skus});
          setSubscriptionIAPs(fetchedSubs);
          setBuyToOwnIAPs(fetchedBTO);
        }
      } catch (error) {
        console.error('Fetch Products Error:', error);
      }
    };
```

I also config on Android: 
`<uses-permission android:name="com.android.vending.BILLING" />`

**Comment by jigar-parmar-13** [comment]
Hello @leminhcse i am also getting same issue can you please help me ?

**Comment by leminhcse** [comment]
> Hello @leminhcse i am also getting same issue can you please help me ?

Hi @jigar-parmar-13 , It's due to the difference between upper and lower case of product Id list from api and product Ids on google play console. 
With google play, all product id must have to define with lowercase (ex: com.minhdoan.myapp.42031.v1) while our product id list from my api are defined with uppercase (com.Minhdoan.Myapp.42031.v1) and when I use getProducts or getSubscriptions from react-native-iap to fetch all product id from google play, they are not match -> return an empty array. 

I think this help you.

**Comment by jigar-parmar-13** [comment]
Okay @leminhcse Thanks for reply, I will check and let you know!
