### ISSUE TITLE
Subscription Bottom Sheet Popup Loop on "Subscribe" Button Click in Sandbox Environment

### ISSUE THREAD

**Issue by Nivashawk** [dooboolab-community/react-native-iap#2796]
**Description**

When clicking the "Subscribe" button in the sandbox environment, the subscription bottom sheet popup appears in a continuous loop, preventing users from completing the subscription process(tested on simulator).

**Steps to Reproduce**

1. Navigate to the subscription page in the sandbox environment.
2. Click on the "Subscribe" button.
3. Observe the subscription bottom sheet popup.

**Expected Behavior**

The subscription bottom sheet should appear once, allowing the user to complete the subscription process.

**Actual Behavior**

The subscription bottom sheet appears in a continuous loop, preventing the user from proceeding with the subscription.

**Screenshots**

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-07-05 at 10 44 00](https://github.com/dooboolab-community/react-native-iap/assets/46569236/9ae35e8a-2667-46e9-a93e-c6ae42aa3aa8)
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-07-05 at 10 44 30](https://github.com/dooboolab-community/react-native-iap/assets/46569236/b89fbc1f-7fed-4fce-9924-4e0fac28b2b0)
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-07-05 at 10 44 50](https://github.com/dooboolab-community/react-native-iap/assets/46569236/d5f7f38a-9422-4044-a1dc-78964e47e566)
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-07-05 at 10 44 53](https://github.com/dooboolab-community/react-native-iap/assets/46569236/f077a496-a519-466c-a3a8-07ecc3fbffa7)

**How We Are Using Your Library**

We are using your library to handle the subscription process as follows:

1. initiating connection
```
 const setupInAppPayment = async () => {
    try {
      await initConnection();
      console.log("IAP connection initialized");
    } catch (err) {
      if (err instanceof Error) {
        console.warn(err.message);
      } else {
        console.warn("Unknown error", err);
      }
    }
  };
  
    React.useEffect(() => {
    setupInAppPayment();
  }, []);
```
2. Getting subscription list
```
  const itemSkus = Platform.select({
    ios: ["m30", "q90", "y365"],
  });

  const getsubs = async () => {
    const subs = await RNIap.getSubscriptions({ skus: itemSkus });
    console.log("subs", subs);
    if (subs.length !== 0) {
      setSubscriptions(subs);
    }
  };
```
3. Initiating request subscription
```
  const purchaseAppleSubscription = async (productId) => {
    try {
        const requestSubscription = await RNIap.requestSubscription({
          sku: productId,
        });
        console.log("requestSubscription", requestSubscription);
      }
    } catch (err) {
      if (err instanceof Error) {
        console.warn(err.message);
        Alert.alert("Purchase Failed", err.message);
      } else {
        console.warn("Unknown error", err);
        Alert.alert("Purchase Failed", "An unknown error occurred");
      }
    }
  };  
```
4. We have a subscription listener 
```
React.useEffect(() => {
    const purchaseUpdateSubscription = RNIap.purchaseUpdatedListener(
      async (purchase) => {
        console.log("purchase", purchase);
        const receipt = purchase.transactionReceipt;
        console.log("receipt", receipt);
        if (receipt && receipt.length !== 0) {
          await axios.post("/user/not", {
            Receipt: receipt,
            Purchase: purchase
          });
          try {
            Alert.alert(
              "Purchase Successful",
              "Thank you for your subscription!"
            );
            await RNIap.finishTransaction({ purchase: purchase });
          } catch (err) {
            if (err instanceof Error) {
              console.warn(err.message);
            } else {
              console.warn("Unknown error", err);
            }
          }
        }
      }
    );
    const purchaseErrorSubscription = RNIap.purchaseErrorListener((error) => {
      console.warn("purchaseErrorListener", error);
      Alert.alert("Purchase Failed", error.message);
    });

    return () => {
      purchaseUpdateSubscription.remove();
      purchaseErrorSubscription.remove();
      // RNIap.endConnection();
    };
  }, []);
```

**Environment:**

- react-native-iap:
- react-native:
- sandbox environment
- Platforms (iOS, Android, emulator, simulator, device):

**Additional Information**

The issue does not occur in the xcode environment.

**Comment by sharukhrahman97** [comment]
Also, the server notifications webhook doesnt get hit, but it is working with [request a test notification](https://developer.apple.com/documentation/appstoreserverapi/request_a_test_notification) and [get test notification status](https://developer.apple.com/documentation/appstoreserverapi/get_test_notification_status).

**Comment by virajpsimformsolutions** [comment]
@sharukhrahman97  
Same Issue I am facing right now. Please share any solution if you have. Thank you in advance.

**Comment by MarkCSmith** [comment]
My experience was that this problem disappears if you use a real device for testing.  I think it may be an Apple bug in the Simulator or the interaction between the Simulator and their services.

**Comment by virajpsimformsolutions** [comment]
Same issue

**Comment by sharukhrahman97** [comment]
Hi, i managed to solve this, you need a real iphone for this for simulation. For some reason apple blocks transactions from simulators even the sandbox transactions. If you have apple silicon you can test directly by installing it as native app and you can test purchases there. Same goes for notifications too.

For webhook you have to check couple of things, check allow list on your server and allow 17.0.0.0/8, then provide your sandbox url (dont use localhost obviously) check v2, and add a storekit config file in your app which links your account, add in app purchase capability and you are good to go!
