### ISSUE TITLE
Getting 21002 at time of verifyReceipt of iOS

### ISSUE THREAD

**Issue by ViralGroovy** [dooboolab-community/react-native-iap#2805]
Hello Dev, Hope you are doing well

**Description**

When I try to verify the Receipt, I get a 21002 error code. Error about 
The data in the receipt-data property was malformed or the service experienced a temporary issue.

**Expected Behavior**

Below response get from request subscription and then I am trying to verify receipt
**Screenshots**
![image](https://github.com/user-attachments/assets/2cdf8d89-9c20-457c-b527-e63669268d3a)

**Environment:**

- "react-native-iap": "12.13.1",
- react-native": "0.73.6",
- Platforms: iOS real device

**Comment by ibraheem88** [comment]
Which Url you are trying to verify receipts? Also your receipts are from sandbox environment or storekit receipts?

**Comment by ViralGroovy** [comment]
I am using RNIap.validateReceiptIos() for verification and environment storekit.

**Comment by ibraheem88** [comment]
Local storekit cannot be verified by sandbox servers. You need to use sandbox receipt to be able to get a valid response from apple server.

**Comment by ViralGroovy** [comment]
![image](https://github.com/user-attachments/assets/ab8ed8e0-789d-4057-a181-23fcfb04b99e)

@ibraheem88 I used now sandbox receipts but still getting same response at a time of verification.

**Comment by ibraheem88** [comment]
Are you passing true to validateReceiptIos like this:
validateReceiptIos(
      {
        receiptBody : receiptBody,
        isTest: true
      }
    )
otherwise it will try to use production servers to validate receipt. Which of course will not work with sandbox receipts.

**Comment by ViralGroovy** [comment]
![image](https://github.com/user-attachments/assets/0a87ab42-6753-483d-87fd-e51a0aa522f3)
![image](https://github.com/user-attachments/assets/7b1a6ed5-e116-48c6-ab49-0d044e922cc0)

@ibraheem88  check this now

**Comment by ibraheem88** [comment]
receiptBody should be of this format:
`const receiptBody = {
      "receipt-data": receipt,
      "password": "##applesecret",
    }`

**Comment by ViralGroovy** [comment]
![image](https://github.com/user-attachments/assets/171fbc61-8d93-48b5-aebb-2f97facccde0)
![image](https://github.com/user-attachments/assets/307fb231-8554-4e16-bdca-8e39836322b0)

@ibraheem88  Already try this one but still getting 21002

**Comment by ibraheem88** [comment]
Confirm that your receipt is from sandbox environment and also check apple secret. You can verify receipt here: [Revenue Cat](https://www.revenuecat.com/app-store-receipt-validation/)

**Comment by ViralGroovy** [comment]
@ibraheem88 check 
![image](https://github.com/user-attachments/assets/f5fed83d-d918-4510-a128-fefe9ec82a8f)

**Comment by ibraheem88** [comment]
You are not getting the receipt the right way I think which method you are using to get receipt. Send the whole snippet

**Comment by ViralGroovy** [comment]
![image](https://github.com/user-attachments/assets/d472c078-bb1e-4d63-8835-a406f33588bb)
![image](https://github.com/user-attachments/assets/7b64b51b-aa36-4650-b5d8-3f7dc6dd55ba)

**Comment by ibraheem88** [comment]
All I can say is this status code normally shows when you are trying to validate storekit receipts.

**Comment by ViralGroovy** [comment]
@ibraheem88 So is there any way to verify local storekit receipts?

**Comment by ibraheem88** [comment]
As far as I know you can only verify sandbox and production receipts.

**Comment by ViralGroovy** [comment]
@ibraheem88  How can we know, We are validating storekit receipts or Sandbox environment transaction receipts?
Is there any way to know about this?

**Comment by ViralGroovy** [comment]
@ibraheem88  Now I remove the store kit file from the root file and try to purchase using the sandbox account now the issue is when I try to get a subscription list of products time get an empty array of the subscription list.

This is my integration steps 
- Create a Product in the app store connect
- Create an account in Sandbox from App Store connect 
- Login with sandbox credential in real device iPhone X
- Open my React native app
- first initial connection successfully done
- then try to get subscription list

**Comment by ibraheem88** [comment]
This issue is different. You can follow this issue here: [Same Issue](https://github.com/dooboolab-community/react-native-iap/issues/723)
