### ISSUE TITLE
iOS: getProducts gets stuck on dev and TestFlight builds

### ISSUE THREAD

**Issue by dimaischenko** [dooboolab-community/react-native-iap#2829]
**Description**

`await getProducts` and `await getSubscriptions` just get stuck and don't return any errors or responses in development and TestFlight builds. Production release from the AppStore is fine.

**Environment:**

- react-native-iap: 12.15.2
- react-native: 0.73.9
- Platforms: iOS

**Comment by jordam1407** [comment]
Is that recent? Few hours ago getSubscriptions was working fine, now it returns Failed to fetch Items.... also iOS

**Comment by mrtawil** [comment]
+1

**Comment by dimaischenko** [comment]
> Is that recent? Few hours ago getSubscriptions was working fine, now it returns Failed to fetch Items.... also iOS

The same. It seems something on the Apple side?

**Comment by dimaischenko** [comment]
@mrtawil @jordam1407 It's been two hours and now everything is working. I didn't make any changes. Sounds like something was on Apple's end

**Comment by dimaischenko** [comment]
It seems that something was on the Apple servers side. But it is worth keeping in mind that this can happen again and even in the AppStore production release builds. So it's good to have an error and stuck handling logic for this case.
