### ISSUE TITLE
Extra argument 'confirmIn' in call

### ISSUE THREAD

**Issue by Alatius** [dooboolab-community/react-native-iap#2830]
**Description**

The code does not compile for me, using Xcode 14.3.1. In RNIapIosSk2.swift, in the code segment
                    if #available(iOS 17.0, tvOS 17.0, *) {
                        result = try await product.purchase(confirmIn: windowScene, options: options)
                    } else {
                        #if !os(visionOS)
                        result = try await product.purchase(options: options)
                        #endif
                    }
I get the compilation error "Extra argument 'confirmIn' in call"

**Environment:**

- react-native-iap: 12.15.2
- react-native: 0.74.4
- Platforms (iOS, Android, emulator, simulator, device): iOS

**Comment by mach-an** [comment]
Same issue for me.

Environment:
- react-native-iap: 12.15.2
- react-native: 0.74.5
- Platforms (iOS, Android, emulator, simulator, device): iOS
