### ISSUE TITLE
[Android] Unable to auto-initialise connection

### ISSUE THREAD

**Issue by Aximem** [dooboolab-community/react-native-iap#2836]
**Description**

I know an issue have already been opened and closed for this issue but it seems the lastest versions of the lib have increased the occurence of it. From rare to often

We upgraded the lib version from 12.10.7 to 12.15.2, without changing our code and this issue is happening from 1 time in a week, to 100 times in a week.

**Environment:**

- react-native-iap: 12.15.2
- react-native: 0.73.1
- Platforms (iOS, Android, emulator, simulator, device): Android

**To Reproduce**

```
useEffect(() => {
    if (connected) { // connected is coming from useIAP hook
      (async () => {
        try {
          if (IS_ANDROID) {
            await flushFailedPurchasesCachedAsPendingAndroid();
          } else {
            await clearTransactionIOS();
          }
          setClearedPendingPurchases(true);
          await getSubscriptions({skus: Object.values(premiumItemSub)});
        } catch (error: any) {
          // Throw Unable to auto-initialise connection
        }
      })();
    }
  }, [connected]);
```

[Optional] **Additional Context**

It seems that users can still be able to get subscriptions after some tries or later.

**Comment by ramakula** [comment]
https://github.com/dooboolab-community/react-native-iap/pull/2839

I added errorCallback where this can be retried.

**Comment by Aximem** [comment]
Thanks for the update but I don't how this is helping for this issue.   
It has been introduced in the latest versions and user who encountered this issue still have the issue after multiple tries, killing app etc. Getting a callback to retry will end to the same error, again and again.
